### ISSUE TITLE
fix example in documentation >> annotations >> upload annotations

### ISSUE THREAD

**Issue by yanirmr** [JavierLuna/pycaprio#12]
The example:

```
from pycaprio.mappings import InceptionFormat, AnnotationState
with open("annotation", 'rb') as annotation_file:
    new_annotation = client.api.create_annotation(1, 4, 'leonardo-dicaprio', annotation_file, annotation_format=InceptionFormat.WEBANNO, annotation_state=AnnotationState.ANNOTATION_IN_PROGRESS)
print(new_annotation) # <Annotation by leonardo-dicaprio (Project: 1, Document: 4)>
```

Make an error:

```
AttributeError: type object 'AnnotationState' has no attribute 'ANNOTATION_IN_PROGRESS'
```

pycaprio version is 0.2.1

**Comment by JavierLuna** [comment]
Hi! Thanks for the issue. It turns out that the automation that updates the documentation website with the actual documentation was broken, and as a result the website was showing quite old docs. 

I believe I fixed it, I couldn't find the bit you are refering to anymore: https://pycaprio.readthedocs.io/en/latest/api/annotations/

Let me know if you find it, please reopen the issue if you still see it (don't forget to clean the cache). Thanks again

**Comment by yanirmr** [comment]
Hi,
I see on two different computers the next code in this page: https://pycaprio.readthedocs.io/en/latest/api/annotations/#upload-annotation
```
from pycaprio.mappings import InceptionFormat, AnnotationState
with open("annotation", 'rb') as annotation_file:
    new_annotation = client.api.create_annotation(1, 4, 'leonardo-dicaprio', annotation_file, annotation_format=InceptionFormat.WEBANNO, annotation_state=AnnotationState.IN_PROGRESS)
print(new_annotation) # <Annotation by leonardo-dicaprio (Project: 1, Document: 4)>
```
